# Generated by Django 4.2 on 2023-04-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('Usename', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=50)),
                ('Num', models.IntegerField()),
                ('year_of_reg', models.DateField(auto_now=True)),
            ],
        ),
    ]
