# Generated by Django 4.2 on 2023-04-29 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fapp', '0004_invoice_prodcategory_product1_delete_product_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User1',
        ),
    ]
