# Generated by Django 4.1.1 on 2023-04-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapp', '0004_invoice_prodcategory_product1_delete_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product1',
            name='pic',
            field=models.FileField(default=0, upload_to='myapp/static/pic'),
        ),
    ]
