# Generated by Django 4.1.1 on 2023-04-30 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapp', '0005_product1_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product1',
            name='pic',
            field=models.FileField(default=0, upload_to='fapp/static/pic'),
        ),
    ]
