# Generated by Django 4.1.7 on 2023-05-02 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fapp', '0005_delete_user1'),
        ('fapp', '0006_alter_product1_pic'),
    ]

    operations = [
    ]
