# Generated by Django 4.1.7 on 2023-05-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapp', '0007_merge_0005_delete_user1_0006_alter_product1_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='User1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('Username', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=50)),
                ('year_of_reg', models.DateField(auto_now=True)),
            ],
        ),
    ]
