# Generated by Django 4.1.7 on 2023-05-02 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fapp', '0008_user1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User1',
        ),
    ]
